// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQvD_kn5s-hlJ_CYAwa6mHtVEh9KjYTY',
    appId: '1:263402661018:web:71e8fd66f24e6ebdf42b23',
    messagingSenderId: '263402661018',
    projectId: 'habittracker-80f5f',
    authDomain: 'habittracker-80f5f.firebaseapp.com',
    storageBucket: 'habittracker-80f5f.firebasestorage.app',
    measurementId: 'G-BGWR6Q0TNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1OLhvXHLSlPKlL0iKC4RFbEr2S4gCr6E',
    appId: '1:263402661018:android:2bc0051d1fd07699f42b23',
    messagingSenderId: '263402661018',
    projectId: 'habittracker-80f5f',
    storageBucket: 'habittracker-80f5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKd3V20PaMVc1Cn1ki80VxzH4QvKGDZCM',
    appId: '1:263402661018:ios:07d98075c749f97ff42b23',
    messagingSenderId: '263402661018',
    projectId: 'habittracker-80f5f',
    storageBucket: 'habittracker-80f5f.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKd3V20PaMVc1Cn1ki80VxzH4QvKGDZCM',
    appId: '1:263402661018:ios:07d98075c749f97ff42b23',
    messagingSenderId: '263402661018',
    projectId: 'habittracker-80f5f',
    storageBucket: 'habittracker-80f5f.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvQvD_kn5s-hlJ_CYAwa6mHtVEh9KjYTY',
    appId: '1:263402661018:web:c1f25c6224f1c9c7f42b23',
    messagingSenderId: '263402661018',
    projectId: 'habittracker-80f5f',
    authDomain: 'habittracker-80f5f.firebaseapp.com',
    storageBucket: 'habittracker-80f5f.firebasestorage.app',
    measurementId: 'G-6D6JFNMZ7P',
  );
}
